on:
  push:
  pull_request:

jobs:
  tsc:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: yarn install (api)
      run: yarn install --immutable
    - name: yarn build (api)
      run: yarn build
    - name: yarn install (frontend)
      working-directory: ./frontend
      run: yarn install --immutable
    - name: yarn build (frontend)
      working-directory: ./frontend
      run: yarn build
